In [1]:
import pandas as pd

In [2]:
hotel_bookings = pd.read_csv('hotel_bookings.csv')

In [3]:
hotel_bookings

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [4]:
hotel_bookings.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [5]:
hotel_bookings.rename({'adults':'num_adults', 'children': 'num_children', 'babies':'num_babies'}, axis=1, inplace=True)

In [6]:
hotel_bookings.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'num_adults', 'num_children', 'num_babies',
       'meal', 'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [11]:
hotel_bookings.isnull().sum()*100/len(hotel_bookings)

hotel                              0.000000
is_canceled                        0.000000
lead_time                          0.000000
arrival_date_year                  0.000000
arrival_date_month                 0.000000
arrival_date_week_number           0.000000
arrival_date_day_of_month          0.000000
stays_in_weekend_nights            0.000000
stays_in_week_nights               0.000000
num_adults                         0.000000
num_children                       0.003350
num_babies                         0.000000
meal                               0.000000
country                            0.408744
market_segment                     0.000000
distribution_channel               0.000000
is_repeated_guest                  0.000000
previous_cancellations             0.000000
previous_bookings_not_canceled     0.000000
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
agent                              0.000000
company                           94.306893
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
reservation_status_date            0.000000
dtype: float64

In [10]:
hotel_bookings['agent'].unique()
hotel_bookings[hotel_bookings['agent']==5]
hotel_bookings['agent'].fillna(-1,inplace=True)
[hotel_bookings['num_children'].isna()]

C:\Users\HP\AppData\Local\Temp\ipykernel_5612\3609981285.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  hotel_bookings['agent'].fillna(-1,inplace=True)

[0         False
 1         False
 2         False
 3         False
 4         False
           ...
 119385    False
 119386    False
 119387    False
 119388    False
 119389    False
 Name: num_children, Length: 119390, dtype: bool]

In [12]:
hotel_bookings[hotel_bookings['country'].isna()][['hotel','is_canceled','country']]

               hotel  is_canceled country
30      Resort Hotel            0     NaN
4127    Resort Hotel            1     NaN
7092    Resort Hotel            1     NaN
7860    Resort Hotel            1     NaN
8779    Resort Hotel            1     NaN
...              ...          ...     ...
65908     City Hotel            1     NaN
65909     City Hotel            1     NaN
65910     City Hotel            1     NaN
80830     City Hotel            0     NaN
101488    City Hotel            0     NaN

[488 rows x 3 columns]

In [14]:
hotel_bookings['country'].fillna('unkown', inplace=True)
hotel_bookings.dropna(subset=['num_children'], inplace=True)
hotel_bookings.drop(column=['company'], inplace=True)

TypeError: DataFrame.drop() got an unexpected keyword argument 'column'

In [15]:
hotel_bookings.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
num_adults                          int64
num_children                      float64
num_babies                          int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
dtype: object

In [17]:
hotel_bookings=hotel_bookings.astype({'is_canceled': 'boolean', 'is_repeated_guest':'boolean', 'num_children':'int', 'agent': 'int'})

In [19]:
hotel_bookings.dtypes

hotel                              object
is_canceled                       boolean
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
num_adults                          int64
num_children                        int32
num_babies                          int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                 boolean
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                               int32
company                           float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
dtype: object

In [21]:
hotel_bookings['lead_time'].unique()

array([342, 737,   7,  13,  14,   0,   9,  85,  75,  23,  35,  68,  18,
        37,  12,  72, 127,  78,  48,  60,  77,  99, 118,  95,  96,  69,
        45,  40,  15,  36,  43,  70,  16, 107,  47, 113,  90,  50,  93,
        76,   3,   1,  10,   5,  17,  51,  71,  63,  62, 101,   2,  81,
       368, 364, 324,  79,  21, 109, 102,   4,  98,  92,  26,  73, 115,
        86,  52,  29,  30,  33,  32,   8, 100,  44,  80,  97,  64,  39,
        34,  27,  82,  94, 110, 111,  84,  66, 104,  28, 258, 112,  65,
        67,  55,  88,  54, 292,  83, 105, 280, 394,  24, 103, 366, 249,
        22,  91,  11, 108, 106,  31,  87,  41, 304, 117,  59,  53,  58,
       116,  42, 321,  38,  56,  49, 317,   6,  57,  19,  25, 315, 123,
        46,  89,  61, 312, 299, 130,  74, 298, 119,  20, 286, 136, 129,
       124, 327, 131, 460, 140, 114, 139, 122, 137, 126, 120, 128, 135,
       150, 143, 151, 132, 125, 157, 147, 138, 156, 164, 346, 159, 160,
       161, 333, 381, 149, 154, 297, 163, 314, 155, 323, 340, 356, 142,
       328, 144, 336, 248, 302, 175, 344, 382, 146, 170, 166, 338, 167,
       310, 148, 165, 172, 171, 145, 121, 178, 305, 173, 152, 354, 347,
       158, 185, 349, 183, 352, 177, 200, 192, 361, 207, 174, 330, 134,
       350, 334, 283, 153, 197, 133, 241, 193, 235, 194, 261, 260, 216,
       169, 209, 238, 215, 141, 189, 187, 223, 284, 214, 202, 211, 168,
       230, 203, 188, 232, 709, 219, 162, 196, 190, 259, 228, 176, 250,
       201, 186, 199, 180, 206, 205, 224, 222, 182, 210, 275, 212, 229,
       218, 208, 191, 181, 179, 246, 255, 226, 288, 253, 252, 262, 236,
       256, 234, 254, 468, 213, 237, 198, 195, 239, 263, 265, 274, 217,
       220, 307, 221, 233, 257, 227, 276, 225, 264, 311, 277, 204, 290,
       266, 270, 294, 319, 282, 251, 322, 291, 269, 240, 271, 184, 231,
       268, 247, 273, 300, 301, 267, 244, 306, 293, 309, 272, 242, 295,
       285, 243, 308, 398, 303, 245, 424, 279, 331, 281, 339, 434, 357,
       325, 329, 278, 332, 343, 345, 360, 348, 367, 353, 373, 374, 406,
       400, 326, 379, 399, 316, 341, 320, 385, 355, 363, 358, 296, 422,
       390, 335, 370, 376, 375, 397, 289, 542, 403, 383, 384, 359, 393,
       337, 362, 365, 435, 386, 378, 313, 351, 287, 471, 462, 411, 450,
       318, 372, 371, 454, 532, 445, 389, 388, 407, 443, 437, 451, 391,
       405, 412, 419, 420, 426, 433, 440, 429, 418, 447, 461, 605, 457,
       475, 464, 482, 626, 489, 496, 503, 510, 517, 524, 531, 538, 545,
       552, 559, 566, 573, 580, 587, 594, 601, 608, 615, 622, 629, 396,
       410, 395, 423, 408, 409, 448, 465, 387, 414, 476, 479, 467, 490,
       493, 478, 504, 507, 458, 518, 521, 377, 444, 380, 463], dtype=int64)

In [22]:
hotel_bookings.describe()

,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,num_adults,num_children,num_babies,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119386.000000,119386.000000,119386.000000,119386.000000,119386.000000,119386.000000,119386.000000,119386.000000,119386.000000,119386.000000,119386.000000,119386.000000,119386.000000,6797.000000,119386.000000,119386.000000,119386.000000,119386.000000
mean,104.014801,2016.156593,27.165003,15.798553,0.927605,2.500310,1.856390,0.103890,0.007949,0.087121,0.137102,0.221131,74.693783,189.266735,2.321227,101.833541,0.062520,0.571340
std,106.863286,0.707456,13.605334,8.780783,0.998618,1.908289,0.579261,0.398561,0.097438,0.844350,1.497462,0.652315,107.239084,131.655015,17.595011,50.534664,0.245295,0.792798
min,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,179.000000,0.000000,94.590000,0.000000,0.000000
75%,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,152.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [24]:
bins=[0,100,200,300,400,500,600,700,800]
labels=['0-100','101-200','201-300','301-400','401-500','501-600','601-700','701-800']
hotel_bookings['lead_time_binned']=pd.cut(hotel_bookings['lead_time'],bins=bins,labels=labels)
hotel_bookings[['lead_time','lead_time_binned']]

        lead_time lead_time_binned
0             342          301-400
1             737          701-800
2               7            0-100
3              13            0-100
4              14            0-100
...           ...              ...
119385         23            0-100
119386        102          101-200
119387         34            0-100
119388        109          101-200
119389        205          201-300

[119386 rows x 2 columns]

In [25]:
hotel_bookings.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,num_adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,lead_time_binned
0,Resort Hotel,False,342,2015,July,27,1,0,0,2,...,-1,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,301-400
1,Resort Hotel,False,737,2015,July,27,1,0,0,2,...,-1,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,701-800
2,Resort Hotel,False,7,2015,July,27,1,0,1,1,...,-1,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,0-100
3,Resort Hotel,False,13,2015,July,27,1,0,1,1,...,304,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,0-100
4,Resort Hotel,False,14,2015,July,27,1,0,2,2,...,240,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03,0-100

In [ ]:
hotel_bookings['arrival_date_month']=hotel_bookings['arrival_date'].str.split('_', expand=True)[0]
hotel_bookings['arrival_date_year']=hotel_bookings['arrival_date'].str.split('_', expand=True)[0]
hotel_bookings.head()

In [ ]:
column_to_move = hotel_bookings.pop('arrival_date_month')
hotel_bookings.insert(4,'arrival_date_month', column_to_move)
hotel_bookings.head()

In [ ]:
column_to_move = hotel_bookings.pop('arrival_date_year')
hotel_bookings.insert(4,'arrival_date_month', column_to_move)
hotel_bookings.head()

In [26]:
hotel_bookings['hotel'].unique()

array(['Resort Hotel', 'City Hotel'], dtype=object)

In [ ]:
hotel_bookings['hotel']=hotel_bookings['hotel'].replace(r,"[\*\n\^]",'',regex=True)

In [27]:
hotel_bookings.duplicated(keep=False)

0         False
1         False
2         False
3         False
4          True
          ...
119385    False
119386    False
119387    False
119388    False
119389    False
Length: 119386, dtype: bool

In [28]:
hotel_bookings.loc[hotel_bookings.duplicated(keep=False)]
hotel_bookings.drop_duplicates(keep="first", inplace=True)